
before_install:
  - perl -V
  - curl -o ./cpanm http://cpanmin.us/
  - perl ./cpanm -l ~/perl5 --verbose --notest --insalldeps .
  - export PERL5LIB=~/perl5/lib/perl5

script:
  perl Makefile.PL && make && make test

jobs:
  include:
    - os: linux
      language: perl
      perl:
        - "5.28"
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11.3
